# This file configures COCOS brokers. 
# MESSAGE_BROKER can be either 'nats' or 'rabbitmq'.
#

services:
  broker:
    extends:
      file: rabbitmq.yml
      service: broker
    container_name: cocos-broker
    restart: on-failure
    networks:
      - cocos-base-net
    volumes:
      - cocos-broker-volume:/data
